// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReservationApp.Services;

#nullable disable

namespace ReservationApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260723223013_AddOwnerUniqueIndex")]
    partial class AddOwnerUniqueIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c0c0c23b-1ceb-4bb2-b0b3-e1212082eba9",
                            Name = "admin",
                            NormalizedName = "admin"
                        },
                        new
                        {
                            Id = "f6d83ba9-e9dc-4202-9976-f4ea848a33fb",
                            Name = "client",
                            NormalizedName = "client"
                        },
                        new
                        {
                            Id = "a1b2c3d4-5e6f-4a7b-8c9d-0e1f2a3b4c5d",
                            Name = "restaurant",
                            NormalizedName = "restaurant"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ReservationApp.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ReservationApp.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Seafood"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Fine Dining"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Fast Food"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Japanese"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Italian"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Cafe"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Steakhouse"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Bistro"
                        });
                });

            modelBuilder.Entity("ReservationApp.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfPeople")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<int?>("TableId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ReservationId");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("TableId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("ReservationApp.Models.Restaurant", b =>
                {
                    b.Property<int>("RestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RestaurantId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("AvgPrice")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OwnerUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RestaurantId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OwnerUserId")
                        .IsUnique()
                        .HasFilter("[OwnerUserId] IS NOT NULL");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            RestaurantId = 1,
                            Address = "12 Shoreline Ave, Seaside",
                            AvgPrice = 75,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "oceans_bounty.jpg",
                            Name = "Ocean's Bounty",
                            PhoneNumber = "555-9876"
                        },
                        new
                        {
                            RestaurantId = 2,
                            Address = "10 Ocean Drive, Shoreline City",
                            AvgPrice = 85,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "fishermans_wharf.jpg",
                            Name = "The Fisherman's Wharf",
                            PhoneNumber = "555-1111"
                        },
                        new
                        {
                            RestaurantId = 3,
                            Address = "22 High Street, Uptown",
                            AvgPrice = 200,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "golden_fork.jpg",
                            Name = "The Golden Fork",
                            PhoneNumber = "555-2345"
                        },
                        new
                        {
                            RestaurantId = 4,
                            Address = "33 Luxury Ave, High Hill",
                            AvgPrice = 250,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "elegance_palace.jpg",
                            Name = "Elegance Palace",
                            PhoneNumber = "555-2222"
                        },
                        new
                        {
                            RestaurantId = 5,
                            Address = "85 Fast Lane, Speedy City",
                            AvgPrice = 15,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "quick_bite.jpg",
                            Name = "QuickBite",
                            PhoneNumber = "555-7654"
                        },
                        new
                        {
                            RestaurantId = 6,
                            Address = "99 Quick Rd, Rushville",
                            AvgPrice = 18,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "speedy_bites.jpg",
                            Name = "Speedy Bites",
                            PhoneNumber = "555-3333"
                        },
                        new
                        {
                            RestaurantId = 7,
                            Address = "4 Blossom Rd, Little Tokyo",
                            AvgPrice = 40,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "sakura_sushi.jpg",
                            Name = "Sakura Sushi",
                            PhoneNumber = "555-3210"
                        },
                        new
                        {
                            RestaurantId = 8,
                            Address = "25 Sakura St, New Kyoto",
                            AvgPrice = 50,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "tokyo_delight.jpg",
                            Name = "Tokyo Delight",
                            PhoneNumber = "555-4444"
                        },
                        new
                        {
                            RestaurantId = 9,
                            Address = "15 Olive St, Old Town",
                            AvgPrice = 60,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "mamma_mia.jpg",
                            Name = "Mamma Mia",
                            PhoneNumber = "555-9087"
                        },
                        new
                        {
                            RestaurantId = 10,
                            Address = "18 Roman Way, Little Italy",
                            AvgPrice = 65,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "pasta_house.jpg",
                            Name = "Pasta House",
                            PhoneNumber = "555-5555"
                        },
                        new
                        {
                            RestaurantId = 11,
                            Address = "9 Coffee Blvd, Downtown",
                            AvgPrice = 12,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "brewed_awakening.jpg",
                            Name = "Brewed Awakening",
                            PhoneNumber = "555-4532"
                        },
                        new
                        {
                            RestaurantId = 12,
                            Address = "44 Bean St, Coffeeville",
                            AvgPrice = 15,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "morning_brew.jpg",
                            Name = "Morning Brew",
                            PhoneNumber = "555-6666"
                        },
                        new
                        {
                            RestaurantId = 13,
                            Address = "34 Beef Rd, Meat District",
                            AvgPrice = 90,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "grill_master.jpg",
                            Name = "Grill Master",
                            PhoneNumber = "555-8723"
                        },
                        new
                        {
                            RestaurantId = 14,
                            Address = "52 Steakhouse Rd, Beef City",
                            AvgPrice = 100,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "prime_cut_grill.jpg",
                            Name = "Prime Cut Grill",
                            PhoneNumber = "555-7777"
                        },
                        new
                        {
                            RestaurantId = 15,
                            Address = "11 Cozy Corner, Riverside",
                            AvgPrice = 45,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "le_petit_bistro.jpg",
                            Name = "Le Petit Bistro",
                            PhoneNumber = "555-6789"
                        },
                        new
                        {
                            RestaurantId = 16,
                            Address = "3 Cozy Ln, Riverside",
                            AvgPrice = 40,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "bistro_bella.jpg",
                            Name = "Bistro Bella",
                            PhoneNumber = "555-8888"
                        });
                });

            modelBuilder.Entity("ReservationApp.Models.RestaurantTable", b =>
                {
                    b.Property<int>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TableId"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<int>("SeatCount")
                        .HasColumnType("int");

                    b.HasKey("TableId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("RestaurantTables");

                    b.HasData(
                        new
                        {
                            TableId = 1,
                            Label = "T1",
                            RestaurantId = 1,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 2,
                            Label = "T2",
                            RestaurantId = 1,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 3,
                            Label = "T3",
                            RestaurantId = 1,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 4,
                            Label = "T4",
                            RestaurantId = 1,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 5,
                            Label = "T5",
                            RestaurantId = 1,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 6,
                            Label = "T6",
                            RestaurantId = 1,
                            SeatCount = 8
                        },
                        new
                        {
                            TableId = 7,
                            Label = "T7",
                            RestaurantId = 1,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 8,
                            Label = "T8",
                            RestaurantId = 1,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 9,
                            Label = "T9",
                            RestaurantId = 1,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 10,
                            Label = "T10",
                            RestaurantId = 1,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 11,
                            Label = "T11",
                            RestaurantId = 1,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 12,
                            Label = "T12",
                            RestaurantId = 1,
                            SeatCount = 8
                        },
                        new
                        {
                            TableId = 13,
                            Label = "T13",
                            RestaurantId = 1,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 14,
                            Label = "T14",
                            RestaurantId = 1,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 15,
                            Label = "T15",
                            RestaurantId = 1,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 16,
                            Label = "T16",
                            RestaurantId = 1,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 17,
                            Label = "T17",
                            RestaurantId = 1,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 18,
                            Label = "T18",
                            RestaurantId = 1,
                            SeatCount = 8
                        },
                        new
                        {
                            TableId = 19,
                            Label = "T19",
                            RestaurantId = 1,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 20,
                            Label = "T20",
                            RestaurantId = 1,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 21,
                            Label = "T21",
                            RestaurantId = 1,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 22,
                            Label = "T22",
                            RestaurantId = 1,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 23,
                            Label = "T23",
                            RestaurantId = 1,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 24,
                            Label = "T24",
                            RestaurantId = 1,
                            SeatCount = 8
                        },
                        new
                        {
                            TableId = 25,
                            Label = "T25",
                            RestaurantId = 1,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 26,
                            Label = "T26",
                            RestaurantId = 1,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 27,
                            Label = "T27",
                            RestaurantId = 1,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 28,
                            Label = "T28",
                            RestaurantId = 1,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 29,
                            Label = "T1",
                            RestaurantId = 2,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 30,
                            Label = "T2",
                            RestaurantId = 2,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 31,
                            Label = "T3",
                            RestaurantId = 2,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 32,
                            Label = "T4",
                            RestaurantId = 2,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 33,
                            Label = "T5",
                            RestaurantId = 2,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 34,
                            Label = "T6",
                            RestaurantId = 2,
                            SeatCount = 8
                        },
                        new
                        {
                            TableId = 35,
                            Label = "T7",
                            RestaurantId = 2,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 36,
                            Label = "T8",
                            RestaurantId = 2,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 37,
                            Label = "T9",
                            RestaurantId = 2,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 38,
                            Label = "T10",
                            RestaurantId = 2,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 39,
                            Label = "T11",
                            RestaurantId = 2,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 40,
                            Label = "T12",
                            RestaurantId = 2,
                            SeatCount = 8
                        },
                        new
                        {
                            TableId = 41,
                            Label = "T13",
                            RestaurantId = 2,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 42,
                            Label = "T14",
                            RestaurantId = 2,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 43,
                            Label = "T15",
                            RestaurantId = 2,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 44,
                            Label = "T16",
                            RestaurantId = 2,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 45,
                            Label = "T17",
                            RestaurantId = 2,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 46,
                            Label = "T18",
                            RestaurantId = 2,
                            SeatCount = 8
                        },
                        new
                        {
                            TableId = 47,
                            Label = "T19",
                            RestaurantId = 2,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 48,
                            Label = "T20",
                            RestaurantId = 2,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 49,
                            Label = "T21",
                            RestaurantId = 2,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 50,
                            Label = "T22",
                            RestaurantId = 2,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 51,
                            Label = "T23",
                            RestaurantId = 2,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 52,
                            Label = "T24",
                            RestaurantId = 2,
                            SeatCount = 8
                        },
                        new
                        {
                            TableId = 53,
                            Label = "T25",
                            RestaurantId = 2,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 54,
                            Label = "T26",
                            RestaurantId = 2,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 55,
                            Label = "T27",
                            RestaurantId = 2,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 56,
                            Label = "T28",
                            RestaurantId = 2,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 57,
                            Label = "T29",
                            RestaurantId = 2,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 58,
                            Label = "T30",
                            RestaurantId = 2,
                            SeatCount = 8
                        },
                        new
                        {
                            TableId = 59,
                            Label = "T31",
                            RestaurantId = 2,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 60,
                            Label = "T32",
                            RestaurantId = 2,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 61,
                            Label = "T33",
                            RestaurantId = 2,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 62,
                            Label = "T34",
                            RestaurantId = 2,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 63,
                            Label = "T35",
                            RestaurantId = 2,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 64,
                            Label = "T36",
                            RestaurantId = 2,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 65,
                            Label = "T1",
                            RestaurantId = 3,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 66,
                            Label = "T2",
                            RestaurantId = 3,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 67,
                            Label = "T3",
                            RestaurantId = 3,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 68,
                            Label = "T4",
                            RestaurantId = 3,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 69,
                            Label = "T5",
                            RestaurantId = 3,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 70,
                            Label = "T6",
                            RestaurantId = 3,
                            SeatCount = 8
                        },
                        new
                        {
                            TableId = 71,
                            Label = "T7",
                            RestaurantId = 3,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 72,
                            Label = "T8",
                            RestaurantId = 3,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 73,
                            Label = "T9",
                            RestaurantId = 3,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 74,
                            Label = "T10",
                            RestaurantId = 3,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 75,
                            Label = "T11",
                            RestaurantId = 3,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 76,
                            Label = "T12",
                            RestaurantId = 3,
                            SeatCount = 8
                        },
                        new
                        {
                            TableId = 77,
                            Label = "T13",
                            RestaurantId = 3,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 78,
                            Label = "T14",
                            RestaurantId = 3,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 79,
                            Label = "T15",
                            RestaurantId = 3,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 80,
                            Label = "T16",
                            RestaurantId = 3,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 81,
                            Label = "T17",
                            RestaurantId = 3,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 82,
                            Label = "T18",
                            RestaurantId = 3,
                            SeatCount = 8
                        },
                        new
                        {
                            TableId = 83,
                            Label = "T19",
                            RestaurantId = 3,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 84,
                            Label = "T1",
                            RestaurantId = 4,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 85,
                            Label = "T2",
                            RestaurantId = 4,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 86,
                            Label = "T3",
                            RestaurantId = 4,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 87,
                            Label = "T4",
                            RestaurantId = 4,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 88,
                            Label = "T5",
                            RestaurantId = 4,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 89,
                            Label = "T6",
                            RestaurantId = 4,
                            SeatCount = 8
                        },
                        new
                        {
                            TableId = 90,
                            Label = "T7",
                            RestaurantId = 4,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 91,
                            Label = "T8",
                            RestaurantId = 4,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 92,
                            Label = "T9",
                            RestaurantId = 4,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 93,
                            Label = "T10",
                            RestaurantId = 4,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 94,
                            Label = "T11",
                            RestaurantId = 4,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 95,
                            Label = "T12",
                            RestaurantId = 4,
                            SeatCount = 8
                        },
                        new
                        {
                            TableId = 96,
                            Label = "T13",
                            RestaurantId = 4,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 97,
                            Label = "T14",
                            RestaurantId = 4,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 98,
                            Label = "T15",
                            RestaurantId = 4,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 99,
                            Label = "T16",
                            RestaurantId = 4,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 100,
                            Label = "T17",
                            RestaurantId = 4,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 101,
                            Label = "T1",
                            RestaurantId = 5,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 102,
                            Label = "T2",
                            RestaurantId = 5,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 103,
                            Label = "T3",
                            RestaurantId = 5,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 104,
                            Label = "T4",
                            RestaurantId = 5,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 105,
                            Label = "T5",
                            RestaurantId = 5,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 106,
                            Label = "T6",
                            RestaurantId = 5,
                            SeatCount = 8
                        },
                        new
                        {
                            TableId = 107,
                            Label = "T7",
                            RestaurantId = 5,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 108,
                            Label = "T8",
                            RestaurantId = 5,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 109,
                            Label = "T9",
                            RestaurantId = 5,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 110,
                            Label = "T10",
                            RestaurantId = 5,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 111,
                            Label = "T11",
                            RestaurantId = 5,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 112,
                            Label = "T12",
                            RestaurantId = 5,
                            SeatCount = 8
                        },
                        new
                        {
                            TableId = 113,
                            Label = "T13",
                            RestaurantId = 5,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 114,
                            Label = "T14",
                            RestaurantId = 5,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 115,
                            Label = "T1",
                            RestaurantId = 6,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 116,
                            Label = "T2",
                            RestaurantId = 6,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 117,
                            Label = "T3",
                            RestaurantId = 6,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 118,
                            Label = "T4",
                            RestaurantId = 6,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 119,
                            Label = "T5",
                            RestaurantId = 6,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 120,
                            Label = "T6",
                            RestaurantId = 6,
                            SeatCount = 8
                        },
                        new
                        {
                            TableId = 121,
                            Label = "T7",
                            RestaurantId = 6,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 122,
                            Label = "T8",
                            RestaurantId = 6,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 123,
                            Label = "T9",
                            RestaurantId = 6,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 124,
                            Label = "T10",
                            RestaurantId = 6,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 125,
                            Label = "T11",
                            RestaurantId = 6,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 126,
                            Label = "T12",
                            RestaurantId = 6,
                            SeatCount = 1
                        },
                        new
                        {
                            TableId = 127,
                            Label = "T1",
                            RestaurantId = 7,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 128,
                            Label = "T2",
                            RestaurantId = 7,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 129,
                            Label = "T3",
                            RestaurantId = 7,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 130,
                            Label = "T4",
                            RestaurantId = 7,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 131,
                            Label = "T5",
                            RestaurantId = 7,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 132,
                            Label = "T6",
                            RestaurantId = 7,
                            SeatCount = 8
                        },
                        new
                        {
                            TableId = 133,
                            Label = "T7",
                            RestaurantId = 7,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 134,
                            Label = "T8",
                            RestaurantId = 7,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 135,
                            Label = "T9",
                            RestaurantId = 7,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 136,
                            Label = "T10",
                            RestaurantId = 7,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 137,
                            Label = "T11",
                            RestaurantId = 7,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 138,
                            Label = "T12",
                            RestaurantId = 7,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 139,
                            Label = "T1",
                            RestaurantId = 8,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 140,
                            Label = "T2",
                            RestaurantId = 8,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 141,
                            Label = "T3",
                            RestaurantId = 8,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 142,
                            Label = "T4",
                            RestaurantId = 8,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 143,
                            Label = "T5",
                            RestaurantId = 8,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 144,
                            Label = "T6",
                            RestaurantId = 8,
                            SeatCount = 8
                        },
                        new
                        {
                            TableId = 145,
                            Label = "T7",
                            RestaurantId = 8,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 146,
                            Label = "T8",
                            RestaurantId = 8,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 147,
                            Label = "T9",
                            RestaurantId = 8,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 148,
                            Label = "T10",
                            RestaurantId = 8,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 149,
                            Label = "T11",
                            RestaurantId = 8,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 150,
                            Label = "T12",
                            RestaurantId = 8,
                            SeatCount = 8
                        },
                        new
                        {
                            TableId = 151,
                            Label = "T13",
                            RestaurantId = 8,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 152,
                            Label = "T14",
                            RestaurantId = 8,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 153,
                            Label = "T1",
                            RestaurantId = 9,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 154,
                            Label = "T2",
                            RestaurantId = 9,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 155,
                            Label = "T3",
                            RestaurantId = 9,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 156,
                            Label = "T4",
                            RestaurantId = 9,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 157,
                            Label = "T5",
                            RestaurantId = 9,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 158,
                            Label = "T6",
                            RestaurantId = 9,
                            SeatCount = 8
                        },
                        new
                        {
                            TableId = 159,
                            Label = "T7",
                            RestaurantId = 9,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 160,
                            Label = "T8",
                            RestaurantId = 9,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 161,
                            Label = "T9",
                            RestaurantId = 9,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 162,
                            Label = "T10",
                            RestaurantId = 9,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 163,
                            Label = "T11",
                            RestaurantId = 9,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 164,
                            Label = "T12",
                            RestaurantId = 9,
                            SeatCount = 8
                        },
                        new
                        {
                            TableId = 165,
                            Label = "T13",
                            RestaurantId = 9,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 166,
                            Label = "T14",
                            RestaurantId = 9,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 167,
                            Label = "T15",
                            RestaurantId = 9,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 168,
                            Label = "T16",
                            RestaurantId = 9,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 169,
                            Label = "T17",
                            RestaurantId = 9,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 170,
                            Label = "T1",
                            RestaurantId = 10,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 171,
                            Label = "T2",
                            RestaurantId = 10,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 172,
                            Label = "T3",
                            RestaurantId = 10,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 173,
                            Label = "T4",
                            RestaurantId = 10,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 174,
                            Label = "T5",
                            RestaurantId = 10,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 175,
                            Label = "T6",
                            RestaurantId = 10,
                            SeatCount = 8
                        },
                        new
                        {
                            TableId = 176,
                            Label = "T7",
                            RestaurantId = 10,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 177,
                            Label = "T8",
                            RestaurantId = 10,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 178,
                            Label = "T9",
                            RestaurantId = 10,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 179,
                            Label = "T10",
                            RestaurantId = 10,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 180,
                            Label = "T11",
                            RestaurantId = 10,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 181,
                            Label = "T12",
                            RestaurantId = 10,
                            SeatCount = 8
                        },
                        new
                        {
                            TableId = 182,
                            Label = "T13",
                            RestaurantId = 10,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 183,
                            Label = "T14",
                            RestaurantId = 10,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 184,
                            Label = "T15",
                            RestaurantId = 10,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 185,
                            Label = "T16",
                            RestaurantId = 10,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 186,
                            Label = "T17",
                            RestaurantId = 10,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 187,
                            Label = "T18",
                            RestaurantId = 10,
                            SeatCount = 8
                        },
                        new
                        {
                            TableId = 188,
                            Label = "T19",
                            RestaurantId = 10,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 189,
                            Label = "T1",
                            RestaurantId = 11,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 190,
                            Label = "T2",
                            RestaurantId = 11,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 191,
                            Label = "T3",
                            RestaurantId = 11,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 192,
                            Label = "T4",
                            RestaurantId = 11,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 193,
                            Label = "T5",
                            RestaurantId = 11,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 194,
                            Label = "T6",
                            RestaurantId = 11,
                            SeatCount = 8
                        },
                        new
                        {
                            TableId = 195,
                            Label = "T7",
                            RestaurantId = 11,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 196,
                            Label = "T8",
                            RestaurantId = 11,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 197,
                            Label = "T9",
                            RestaurantId = 11,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 198,
                            Label = "T1",
                            RestaurantId = 12,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 199,
                            Label = "T2",
                            RestaurantId = 12,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 200,
                            Label = "T3",
                            RestaurantId = 12,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 201,
                            Label = "T4",
                            RestaurantId = 12,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 202,
                            Label = "T5",
                            RestaurantId = 12,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 203,
                            Label = "T6",
                            RestaurantId = 12,
                            SeatCount = 8
                        },
                        new
                        {
                            TableId = 204,
                            Label = "T7",
                            RestaurantId = 12,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 205,
                            Label = "T8",
                            RestaurantId = 12,
                            SeatCount = 3
                        },
                        new
                        {
                            TableId = 206,
                            Label = "T1",
                            RestaurantId = 13,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 207,
                            Label = "T2",
                            RestaurantId = 13,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 208,
                            Label = "T3",
                            RestaurantId = 13,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 209,
                            Label = "T4",
                            RestaurantId = 13,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 210,
                            Label = "T5",
                            RestaurantId = 13,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 211,
                            Label = "T6",
                            RestaurantId = 13,
                            SeatCount = 8
                        },
                        new
                        {
                            TableId = 212,
                            Label = "T7",
                            RestaurantId = 13,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 213,
                            Label = "T8",
                            RestaurantId = 13,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 214,
                            Label = "T9",
                            RestaurantId = 13,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 215,
                            Label = "T10",
                            RestaurantId = 13,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 216,
                            Label = "T11",
                            RestaurantId = 13,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 217,
                            Label = "T12",
                            RestaurantId = 13,
                            SeatCount = 8
                        },
                        new
                        {
                            TableId = 218,
                            Label = "T13",
                            RestaurantId = 13,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 219,
                            Label = "T14",
                            RestaurantId = 13,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 220,
                            Label = "T15",
                            RestaurantId = 13,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 221,
                            Label = "T16",
                            RestaurantId = 13,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 222,
                            Label = "T17",
                            RestaurantId = 13,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 223,
                            Label = "T18",
                            RestaurantId = 13,
                            SeatCount = 8
                        },
                        new
                        {
                            TableId = 224,
                            Label = "T19",
                            RestaurantId = 13,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 225,
                            Label = "T20",
                            RestaurantId = 13,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 226,
                            Label = "T21",
                            RestaurantId = 13,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 227,
                            Label = "T1",
                            RestaurantId = 14,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 228,
                            Label = "T2",
                            RestaurantId = 14,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 229,
                            Label = "T3",
                            RestaurantId = 14,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 230,
                            Label = "T4",
                            RestaurantId = 14,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 231,
                            Label = "T5",
                            RestaurantId = 14,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 232,
                            Label = "T6",
                            RestaurantId = 14,
                            SeatCount = 8
                        },
                        new
                        {
                            TableId = 233,
                            Label = "T7",
                            RestaurantId = 14,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 234,
                            Label = "T8",
                            RestaurantId = 14,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 235,
                            Label = "T9",
                            RestaurantId = 14,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 236,
                            Label = "T10",
                            RestaurantId = 14,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 237,
                            Label = "T11",
                            RestaurantId = 14,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 238,
                            Label = "T12",
                            RestaurantId = 14,
                            SeatCount = 8
                        },
                        new
                        {
                            TableId = 239,
                            Label = "T13",
                            RestaurantId = 14,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 240,
                            Label = "T14",
                            RestaurantId = 14,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 241,
                            Label = "T15",
                            RestaurantId = 14,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 242,
                            Label = "T16",
                            RestaurantId = 14,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 243,
                            Label = "T17",
                            RestaurantId = 14,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 244,
                            Label = "T18",
                            RestaurantId = 14,
                            SeatCount = 8
                        },
                        new
                        {
                            TableId = 245,
                            Label = "T19",
                            RestaurantId = 14,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 246,
                            Label = "T20",
                            RestaurantId = 14,
                            SeatCount = 1
                        },
                        new
                        {
                            TableId = 247,
                            Label = "T1",
                            RestaurantId = 15,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 248,
                            Label = "T2",
                            RestaurantId = 15,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 249,
                            Label = "T3",
                            RestaurantId = 15,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 250,
                            Label = "T4",
                            RestaurantId = 15,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 251,
                            Label = "T5",
                            RestaurantId = 15,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 252,
                            Label = "T6",
                            RestaurantId = 15,
                            SeatCount = 8
                        },
                        new
                        {
                            TableId = 253,
                            Label = "T7",
                            RestaurantId = 15,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 254,
                            Label = "T1",
                            RestaurantId = 16,
                            SeatCount = 6
                        },
                        new
                        {
                            TableId = 255,
                            Label = "T2",
                            RestaurantId = 16,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 256,
                            Label = "T3",
                            RestaurantId = 16,
                            SeatCount = 4
                        },
                        new
                        {
                            TableId = 257,
                            Label = "T4",
                            RestaurantId = 16,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 258,
                            Label = "T5",
                            RestaurantId = 16,
                            SeatCount = 2
                        },
                        new
                        {
                            TableId = 259,
                            Label = "T6",
                            RestaurantId = 16,
                            SeatCount = 7
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ReservationApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ReservationApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservationApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ReservationApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReservationApp.Models.Reservation", b =>
                {
                    b.HasOne("ReservationApp.Models.Restaurant", "Restaurant")
                        .WithMany("Reservation")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservationApp.Models.RestaurantTable", "Table")
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ReservationApp.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Restaurant");

                    b.Navigation("Table");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReservationApp.Models.Restaurant", b =>
                {
                    b.HasOne("ReservationApp.Models.Category", "Category")
                        .WithMany("Restaurants")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReservationApp.Models.ApplicationUser", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("ReservationApp.Models.RestaurantTable", b =>
                {
                    b.HasOne("ReservationApp.Models.Restaurant", "Restaurant")
                        .WithMany("Tables")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("ReservationApp.Models.Category", b =>
                {
                    b.Navigation("Restaurants");
                });

            modelBuilder.Entity("ReservationApp.Models.Restaurant", b =>
                {
                    b.Navigation("Reservation");

                    b.Navigation("Tables");
                });
#pragma warning restore 612, 618
        }
    }
}
